packages:
  # - 'apps/*'
  - 'packages/*'
  - 'scripts/*'
  - website
catalog:
  "@babel/generator": "^7.26.8"
  "@babel/parser": "^7.26.8"
  "@babel/traverse": "^7.26.8"
  "@babel/types": "^7.26.8"
  "magic-string": "^0.30.17"
  "pathe": "^2.0.2"
  "postcss": "^8.5.1"
  "fs-extra": "^11.3.0"
  "is-css-request": "^1.0.1"
  "unplugin": "^2.1.2"
catalogs:
  tailwindcss3:
    "tailwindcss": "^3.4.17"
  tailwindcss4:
    "tailwindcss": "^4.0.5"